### ISSUE TITLE
Sidebar menu toggle not working

### ISSUE THREAD

**Issue by pptyasar** [dmstr/yii2-adminlte-asset#147]
```
jquery.js:9823 Uncaught TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (jquery.js:9823)
    at app.js:156

jquery.js:3860 jQuery.Deferred exception: $(...).tree is not a function TypeError: $(...).tree is not a function

    at HTMLDocument.<anonymous> (http://localhost/annam/backend/web/assets/e9dbdd41/admin-lte/js/AdminLTE/app.js:96:29)
    at mightThrow (http://localhost/annam/backend/web/assets/c2e430bd/jquery.js:3583:29)
    at process (http://localhost/annam/backend/web/assets/c2e430bd/jquery.js:3651:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3860
jquery.js:3869 Uncaught TypeError: $(...).tree is not a function
    at HTMLDocument.<anonymous> (app.js:96)
    at mightThrow (jquery.js:3583)
    at process (jquery.js:3651)
/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by aagge** [comment]
Add 'data-widget' => 'tree' to the options in sidebar menu. It should now look like this:-

'options' => ['class' => 'sidebar-menu', 'data-widget' => 'tree'],

**Comment by gomonkey** [comment]
I have the same problem and data-widget is not have effect to me

**Comment by gomonkey** [comment]
I solved to update following this  [139](https://github.com/dmstr/yii2-adminlte-asset/issues/139)

**Comment by anish-adm** [comment]
Awesome! @aagge's solution worked for me!

**Comment by schmunk42** [comment]
Any objections adding above default `options` to the menu widget?
